site_name: Semi-Humanoid Documentation
nav:
    - Home: index.md
    - Speech: speech.md
    - Chatbot: chat.md
    - Slam: slam.md
    - Actions: actions.md
    - Design; design.md
theme: readthedocs
